### ISSUE TITLE
Query execute then cache is null. Please help!

### ISSUE THREAD

**Issue by icednut** [matsientst/dewdrop#9]
Hi, I wrote todo app with dewdrop. When I was quering Todo Item, ReadModel cache is empty. Can I get some help with this issue?
Please review my dewdrop example code and issue.
https://github.com/icednut/todo-with-dewdrop/blob/master/src/main/java/io/icednut/dewdrop/exercise/query/TodoReadModel.java#L24

**Comment by matsientst** [comment]
We'll be looking into this and will get back to you in a day or so.
Thanks for checking out Dewdrop!

**Comment by matsientst** [comment]
@icednut You did great on this example. The issue you are seeing is that you need to mark your creation event with the `@CreationEvent` annotation:

```
@CreationEvent
public class TodoItemCreated extends TodoEvent {}
```
And, I would move the `@EventHandler` to the DTO itself like this:

```
public class TodoItemDetails {

    @PrimaryCacheKey
    private UUID todoItemId;
    private String content;
    public TodoItemDetails() {
        super();
    }

    @EventHandler
    public void on(TodoItemCreated event) {
        this.todoItemId = event.getTodoItemId();
        this.content = event.getContent();
    }

    public UUID getTodoItemId() {
        return todoItemId;
    }

    public String getContent() {
        return content;
    }
}

```
I tried your code and when you make those two changes the tests pass. Let me know if you need any more help!
Thank you for checking it out!

**Comment by matsientst** [comment]
@icednut You did great on this example. The issue you are seeing is that you need to mark your creation event with the `@CreationEvent` annotation:

```
@CreationEvent
public class TodoItemCreated extends TodoEvent {}
```
This lets the cache know when to create a new cache entry, rather than to look for one to update.


And, I would move the `@EventHandler` to the DTO itself like this:

```
public class TodoItemDetails {

    @PrimaryCacheKey
    private UUID todoItemId;
    private String content;
    public TodoItemDetails() {
        super();
    }

    @EventHandler
    public void on(TodoItemCreated event) {
        this.todoItemId = event.getTodoItemId();
        this.content = event.getContent();
    }

    public UUID getTodoItemId() {
        return todoItemId;
    }

    public String getContent() {
        return content;
    }
}

```
I tried your code and when you make those two changes the tests pass. Let me know if you need any more help!
Thank you for checking it out!

**Comment by icednut** [comment]
Thank you. I'll try it.

**Comment by icednut** [comment]
@matsientst 
Thank you. I'll try it.
